--EXISTEN FUNCIONES NATIVAS PARA REALIZAR OPERACIONES

--CONTAR LA CANTIDAD DE TAREAS POR USUARIO --COUNT
SELECT U.NAME, COUNT(*)
FROM TASKS T,
     USERS U
WHERE T.USER_ID = U.ID
GROUP BY U.NAME;

SELECT COUNT(*)
FROM TASKS

-- FUNCTION PARA FECHAS
SELECT NOW()

--FUNCIONES PARA CADENAS
--CONVERTIR A MAYUSCULAS
SELECT UPPER(U.NAME)
FROM USERS U

--SUBSTRING
SELECT CONCAT(SUBSTRING(U.NAME FROM 1 FOR 3), '2025@GMAI.COM')
FROM USERS U