--LENGUAJE SQL (LEXICO, SINTAXIS, SEMANTICO)
--DLL - LENGUAJE DEFINION DATOS
--DML - LENGUAJE MANIPULACION DATOS

-- CRUD (CREATE, READ, UPDATE,DELETE)

--comentarios
--RESTRICCIONES (LLAVE PRIMARIA, VALOR, LIMITE, LLAVE FORANEA)

CREATE TABLE pais(
  id SERIAL PRIMARY KEY UNIQUE NOT NULL, 
  nombre VARCHAR(30)
);

CREATE TABLE presidente(
id SERIAL PRIMARY KEY UNIQUE NOT NULL, 
nombre VARCHAR(30),
id_pais INTEGER UNIQUE,
FOREIGN KEY(id_pais) REFERENCES pais(id)
)

CREATE TABLE CLIENTE(
id SERIAL PRIMARY KEY UNIQUE NOT NULL, 
nombre VARCHAR(30)
);

CREATE TABLE FACTURA(
id SERIAL PRIMARY KEY UNIQUE NOT NULL, 
fecha DATE,
id_cliente INTEGER,
FOREIGN KEY(id_cliente) REFERENCES cliente(id)
);

INSERT INTO CLIENTE(nombre) VALUES
('jhon'),
('juan'),
('pedro');

INSERT INTO FACTURA(fecha,id_cliente) VALUES
('2025-06-15',1),
('2025-06-16',1),
('2025-06-17',2),
('2025-06-18',1),
('2025-06-19',3);




